# Generated by Django 5.2.17 on 2026-09-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Rajwadi Ornaments', max_length=150)),
                ('tagline', models.CharField(default='Royal Heritage Jewellery of Gujarat', max_length=250)),
                ('whatsapp_number', models.CharField(default='+919876543210', help_text='WhatsApp phone number with country code, e.g. +919876543210', max_length=20)),
                ('phone_number', models.CharField(default='+919876543210', help_text='Contact number for direct voice calls', max_length=20)),
                ('email', models.EmailField(default='contact@rajwadiornaments.com', max_length=254)),
                ('address', models.TextField(default='Showroom No. 12, Heritage Jewellery Market, C.G. Road, Ahmedabad, Gujarat 380009')),
                ('city', models.CharField(default='Ahmedabad, Gujarat', max_length=100)),
                ('business_hours', models.CharField(default='Mon – Sat: 10:30 AM – 8:30 PM | Sunday: By Appointment', max_length=200)),
                ('about_summary', models.TextField(default='Rajwadi Ornaments celebrates the centuries-old royal craftsmanship of Gujarat and Rajasthan. From intricate Jadau and Kundan bridal masterpieces to timeless Kathiyawadi jhumkas and pachchikam rings, each piece is handcrafted with supreme elegance and authentic heritage.')),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com')),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business Setting',
                'verbose_name_plural': 'Business Settings',
            },
        ),
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=25)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('category_interest', models.CharField(blank=True, default='', max_length=100)),
                ('ornament_name', models.CharField(blank=True, default='', max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
