# Generated by Django 5.2.17 on 2026-09-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesssettings',
            name='about_summary',
            field=models.TextField(default='Zivara brings authentic Gujarat traditional ornaments directly to your doorstep. When you select an ornament, your order is processed by Zivara and shipped directly from Gujarat to your address. From intricate Jadau and Kundan pieces to timeless Kathiyawadi necklaces, bridal sets, and bangles, we deliver authentic Gujarat heritage jewellery with guaranteed doorstep delivery.'),
        ),
        migrations.AlterField(
            model_name='businesssettings',
            name='address',
            field=models.TextField(default='Gujarat, India (Direct Shipment Hub)'),
        ),
        migrations.AlterField(
            model_name='businesssettings',
            name='business_hours',
            field=models.CharField(default='Monday – Saturday: 9:30 AM – 7:30 PM | Available on WhatsApp & Call', max_length=200),
        ),
        migrations.AlterField(
            model_name='businesssettings',
            name='city',
            field=models.CharField(default='Gujarat, India', max_length=100),
        ),
        migrations.AlterField(
            model_name='businesssettings',
            name='email',
            field=models.EmailField(default='contact@zivaraornaments.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='businesssettings',
            name='phone_number',
            field=models.CharField(default='+918848242986', help_text='Contact number for direct voice calls', max_length=20),
        ),
        migrations.AlterField(
            model_name='businesssettings',
            name='store_name',
            field=models.CharField(default='Zivara', max_length=150),
        ),
        migrations.AlterField(
            model_name='businesssettings',
            name='tagline',
            field=models.CharField(default='Gujarat Traditional Ornaments • Shipped Directly from Gujarat', max_length=250),
        ),
        migrations.AlterField(
            model_name='businesssettings',
            name='whatsapp_number',
            field=models.CharField(default='+918848242986', help_text='WhatsApp phone number, e.g. +91 8848242986', max_length=20),
        ),
    ]
