# Generated by Django 5.2.17 on 2026-09-22 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Ornament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(help_text='Detailed description of the ornament, craftsmanship and design')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price in INR (leave blank if on request)', max_digits=12, null=True)),
                ('is_price_on_request', models.BooleanField(default=False, help_text="Show 'Price on Request' instead of exact amount")),
                ('availability', models.CharField(choices=[('in_stock', 'In Stock'), ('made_to_order', 'Made to Order'), ('out_of_stock', 'Out of Stock')], default='in_stock', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this ornament on homepage')),
                ('purity', models.CharField(blank=True, default='22K Gold', help_text='e.g. 22K Gold, Polki, Kundan, Antique', max_length=100)),
                ('weight_approx', models.CharField(blank=True, default='', help_text='Approximate weight, e.g. 35g', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ornaments', to='ornaments.category')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrnamentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ornaments/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ornament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ornaments.ornament')),
            ],
            options={
                'ordering': ['-is_primary', 'display_order', 'id'],
            },
        ),
    ]
